/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Lanjutan extends javax.swing.JFrame {

    /**
     * Creates new form Lanjutan
     */
    public Lanjutan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TggBalok = new javax.swing.JTextField();
        LbrBalok = new javax.swing.JTextField();
        PjgBalok = new javax.swing.JTextField();
        balok = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Sisi = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Jari = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Program Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 40, 220, 20);

        jPanel2.setLayout(null);

        jLabel2.setText("Masukkan Panjang :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 20, 130, 14);

        jLabel4.setText("Masukkan Lebar     :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 60, 110, 14);

        jLabel5.setText("Masukkan Tinggi    :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 100, 110, 14);
        jPanel2.add(TggBalok);
        TggBalok.setBounds(140, 100, 180, 30);

        LbrBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LbrBalokActionPerformed(evt);
            }
        });
        jPanel2.add(LbrBalok);
        LbrBalok.setBounds(140, 60, 180, 30);

        PjgBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PjgBalokActionPerformed(evt);
            }
        });
        jPanel2.add(PjgBalok);
        PjgBalok.setBounds(140, 20, 180, 30);

        balok.setText("Hitung");
        balok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balokActionPerformed(evt);
            }
        });
        jPanel2.add(balok);
        balok.setBounds(140, 140, 80, 30);

        jTabbedPane2.addTab("Balok", jPanel2);

        jPanel3.setLayout(null);

        jLabel6.setText("cm");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(100, 50, 150, 30);

        jLabel9.setText("Masukkan panjang Sisi");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 30, 150, 14);

        jButton3.setText("Volume");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(20, 90, 90, 30);
        jPanel3.add(Sisi);
        Sisi.setBounds(20, 50, 70, 30);

        jTabbedPane2.addTab("Kubus", jPanel3);

        jPanel4.setLayout(null);
        jPanel4.add(jLabel3);
        jLabel3.setBounds(182, 5, 0, 0);

        jLabel7.setText("Masukkan Panjang Jari-jari :");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(20, 20, 160, 14);

        Jari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JariActionPerformed(evt);
            }
        });
        jPanel4.add(Jari);
        Jari.setBounds(20, 40, 80, 30);

        jLabel8.setText("cm");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(110, 40, 40, 30);

        jButton2.setText("Volume");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(20, 80, 80, 30);

        jTabbedPane2.addTab("Bola", jPanel4);

        getContentPane().add(jTabbedPane2);
        jTabbedPane2.setBounds(20, 80, 370, 200);

        setBounds(0, 0, 416, 377);
    }// </editor-fold>//GEN-END:initComponents

    private void LbrBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LbrBalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LbrBalokActionPerformed

    private void PjgBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PjgBalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PjgBalokActionPerformed

    private void balokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balokActionPerformed
        // TODO add your handling code here:
        int panjang , lebar , tinggi;
        panjang = Integer.parseInt(PjgBalok.getText());
        lebar = Integer.parseInt(LbrBalok.getText());
        tinggi = Integer.parseInt(TggBalok.getText());
        int hasil = panjang*lebar*tinggi;
        try{
            JOptionPane.showMessageDialog(null,"Volume Balok adalah : "+hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error : "+e,"Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_balokActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi = Integer.parseInt(Sisi.getText());
        int hasil = sisi*sisi*sisi;
        
        try{
            JOptionPane.showMessageDialog(null,"Luas Permukaan Kubus Adalah : "+hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error : "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void JariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JariActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_JariActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        float jari;
        jari = Integer.parseInt(Jari.getText());
        float hasil1 = (float) (4/3*3.14*jari*jari*jari);
        try{
            JOptionPane.showMessageDialog(null,"Luas Permukaan Bola Adalah : "+hasil1,"luas",JOptionPane.INFORMATION_MESSAGE);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error : "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lanjutan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lanjutan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lanjutan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lanjutan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lanjutan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jari;
    private javax.swing.JTextField LbrBalok;
    private javax.swing.JTextField PjgBalok;
    private javax.swing.JTextField Sisi;
    private javax.swing.JTextField TggBalok;
    private javax.swing.JButton balok;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
