/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author User
 */
public class Latihan1 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan1
     */
    public Latihan1() {
        initComponents();
        int b1 , b2 , b3 , b4 , d ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        brg2 = new javax.swing.JTextField();
        brg1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        diskon = new javax.swing.JTextField();
        brg3 = new javax.swing.JTextField();
        hapus = new javax.swing.JButton();
        brg4 = new javax.swing.JTextField();
        keluar = new javax.swing.JButton();
        proses = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Pembayaran");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 20, 80, 20);

        jLabel3.setText("Harga Barang 4");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 180, 90, 14);

        brg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brg2ActionPerformed(evt);
            }
        });
        getContentPane().add(brg2);
        brg2.setBounds(130, 100, 180, 30);

        brg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brg1ActionPerformed(evt);
            }
        });
        getContentPane().add(brg1);
        brg1.setBounds(130, 60, 180, 30);

        jLabel5.setText(" Harga Barang 2");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 100, 90, 14);

        jLabel6.setText("Harga Barang 3");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 140, 90, 14);

        total.setText("Hasil");
        getContentPane().add(total);
        total.setBounds(60, 320, 90, 20);

        jLabel8.setText("Harga Barang 1");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 60, 90, 14);

        diskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskonActionPerformed(evt);
            }
        });
        getContentPane().add(diskon);
        diskon.setBounds(130, 220, 180, 30);

        brg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brg3ActionPerformed(evt);
            }
        });
        getContentPane().add(brg3);
        brg3.setBounds(130, 140, 180, 30);

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(143, 280, 80, 23);

        brg4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brg4ActionPerformed(evt);
            }
        });
        getContentPane().add(brg4);
        brg4.setBounds(130, 180, 180, 30);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(253, 280, 70, 23);

        proses.setText("Proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses);
        proses.setBounds(35, 280, 80, 23);

        jLabel9.setText("Diskon");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 220, 90, 14);

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane2.setViewportView(hasil);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(50, 340, 280, 110);

        setBounds(0, 0, 416, 529);
    }// </editor-fold>//GEN-END:initComponents

    private void brg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brg2ActionPerformed
        // TODO add your handling code here:
        int b2 = Integer.valueOf(brg2.getText());
    }//GEN-LAST:event_brg2ActionPerformed

    private void brg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brg1ActionPerformed
        // TODO add your handling code here:
        int b1 = Integer.valueOf(brg1.getText());
    }//GEN-LAST:event_brg1ActionPerformed

    private void diskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskonActionPerformed
        // TODO add your handling code here:
        int d = Integer.valueOf(diskon.getText());

    }//GEN-LAST:event_diskonActionPerformed

    private void brg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brg3ActionPerformed
        // TODO add your handling code here:
        int b3 = Integer.valueOf(brg3.getText());
    }//GEN-LAST:event_brg3ActionPerformed

    private void brg4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brg4ActionPerformed
        // TODO add your handling code here:
        int b4 = Integer.valueOf(brg4.getText());
    }//GEN-LAST:event_brg4ActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
       int b1 = Integer.valueOf(brg1.getText());
       int b2 = Integer.valueOf(brg2.getText());
       int b3 = Integer.valueOf(brg3.getText());
       int b4 = Integer.valueOf(brg4.getText());
       int d = Integer.valueOf(diskon.getText());
        // TODO add your handling code here:
        int harga = (b1+b2+b3+b4);
        
       hasil.setText("Harga Barang 1 : "+b1+"\nHarga Barang 2 : "+b2+"\nHarga Barang 3 : "+b3+"\nHarga Barang 4 : "+b4+"\nDiskon Anda : "+diskon+"\nTotal Harga : "+harga);

    }//GEN-LAST:event_prosesActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        brg1.setText(" ");
        brg2.setText(" ");
        brg3.setText(" ");
        brg4.setText(" ");
        diskon.setText(" ");
    }//GEN-LAST:event_hapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brg1;
    private javax.swing.JTextField brg2;
    private javax.swing.JTextField brg3;
    private javax.swing.JTextField brg4;
    private javax.swing.JTextField diskon;
    private javax.swing.JButton hapus;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton keluar;
    private javax.swing.JButton proses;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
